### ISSUE TITLE
Connect two wifi enabled devices

### ISSUE THREAD

**Issue by Coder-iOS** [robbiehanson/CocoaAsyncSocket#439]
Can I connect two iOS device over wifi where two device are not connected to any wifi router.

Please suggest.

**Comment by chrisballinger** [comment]
Look into the MultipeerConnectivity framework

**Comment by nbegley23** [comment]
Can anyone elaborate on this a little?  I've found that the MultipeerConnectivity framework is a real piece of garbage when it comes to transferring large files (speeds often level out around 200 kbps) and I'd like to avoid just using straight up NSStreams as that is it's own headache.  I've gotten as far as advertising and resolving addresses between two devices that have wi-fi on but are not connected to anything by using NSNetService with includesPeerToPeer set to YES, but as soon as I try and connect to the server GCDAsyncSocket using the server address provided by the NSNetService resolving on the client side, the library doesn't do anything.  No errors, no timing out, nothing.

**Comment by xaphod** [comment]
nbegley23: If you're using NSNetService, then you're not going to see better perf on wifi than multipeer, unless you are able to permanently stopAdvertising() once you're connected. 
I'm in the middle of tying together HHServices (https://github.com/tolo/HHServices) and GCDAsyncSocket to create an alternative to Multipeer. My reason is because I need to limit it to bluetooth-only, precisely because of the wifi speed issue. But of course, bluetooth speed is much worse than wifi. In my case that's ok: i don't have much to transfer, but I cannot harm the wifi speed as much as multipeer does (and I cannot ever stop advertising for peers)

**Comment by danielbotka** [comment]
@nbegley23 have you found any solutions for this issue? I tried many things and I agree with you, NSNetServices a lot lot faster on Wifi than multipeer, but can't make it work between two devices without a wifi router. Basically I'm at the same situation you are.

**Comment by danielbotka** [comment]
Yes, but actually this is exactly what I need. NSNetServices and GCDAsyncSocket works wonderfully and super fast together, when I have an access point. With peer to peer options I can discover these services, (so I can retrieve the hosts, without any access point or BLE) but I'm stuck with an error message, and it happens only with peer-to-peer connections. GCDAsyncSocket can't connect to the peer-to-peer host for some reason and errors out. I'll probably open a new ticket with the error, hopefully someone can help me with this problem.
