### ISSUE TITLE
Why can't I receive data after a few minutes?

### ISSUE THREAD

**Issue by leozhuo** [robbiehanson/CocoaAsyncSocket#604]
I can receive data after my project runs.  But after a few minutes,  i can't receive the data. There is no print disconnect information. Can you tell me how to do it?

**Comment by Yuzeyang** [comment]
You can use ` tcpdump -i any -n -X port [port] ` to determine if there is data sent from the server to the local.

**Comment by fafoulon** [comment]
Hi, I have the same behavior since few weeks. At first I thought it was my change from DSL to Fiber, but I see I'm not alone. I always had a stable connection, but now it's not getting any data after 10-20 minutes. Another app is connected to the server via LAN, and has no problem. It's only via Internet

**Comment by fafoulon** [comment]
Anyone having any idea about this?
