### ISSUE TITLE
The app references non-public selectors in Payload

### ISSUE THREAD

**Issue by nielsoo** [robbiehanson/CocoaAsyncSocket#672]
Hi, am I the only one receiving warnings about non-public selectors since a few days when uploading apps to itunesconnect (testflight)? (probably my next app submission will get rejected for this) 

this is the warning I get, and these selectors are only used by CocoaAsyncSocket in my project:

The app references non-public selectors in Payload/<appName> newSocketQueueForConnectionFromAddress:onSocket:, socket:didAcceptNewSocket:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:

**Comment by zhuyajing001** [comment]
also，the same problem.the question is ,i have to apps.one upload is ok ,the other is The app references non-public .two apps,both use the CocoaAsyncSocket.i whant to knwo why!

**Comment by zhuyajing001** [comment]
the app was payloaded，this question does not have effect on app.but why this happed ?

**Comment by JensvdHeydt** [comment]
I'm having the same problem with my app. Does anybody have a solution?

**Comment by seanm** [comment]
The list @nielsoo gave are all CocoaAsyncSocket methods, not Apple methods.  Surely this is just a false positive from whatever Apple is using.  Seems you should complain to them.

**Comment by fansanelli** [comment]
Hello,

I'm experiencing the same issue...
I also would mention that there are lots of warnings:
[-Wblock-capture-autoreleasing]
[-Wdeprecated-declarations]
[-Wdeprecated-implementations]
[-Wimplicit-retain-self]
[-Wstrict-prototypes]

Could one of these cause the problem?
I've read a similar issue was due to a LLVM linker's setting, how can this be investigated?
Many thanks
Cheers
Francesco

**Comment by sidhisan** [comment]
Hi all, this issue fixed for me by setting Enable Bitcode as true

**Comment by charmingtoad** [comment]
I'm experiencing the same issue. I cannot try enabling bitcode, because a different dependency I'm using was built without it.

Apple's rejection states "If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. "

Even though it is a false positive, Apple asks developers to resolve it by renaming methods that match private Apple APIs.

**Comment by Sega-Zero** [comment]
having the same issue on XCode 14 even with bitcode is enabled (which is reasonable: bitcode has been deprecated)

**Comment by skam22** [comment]
same issue here on Xcode 14.

**Comment by Sega-Zero** [comment]
the project seems stalled. solved the problem by removing from project

**Comment by landonhughes** [comment]
+1 for same issue with Xcode 14

**Comment by dishank-betaflux** [comment]
same issue coming
