### ISSUE TITLE
About iOS 14 Local Network Privacy

### ISSUE THREAD

**Issue by 0x5e** [robbiehanson/CocoaAsyncSocket#726]
Any discussion about this? There's API for URLSession and NWConnection to block the request until user click the allow button, but socket can't handle this. And there's no API to get permission status before the request.

https://developer.apple.com/videos/play/wwdc2020/10110/
https://developer.apple.com/forums/tags/wwdc20-10110

**Comment by scinfu** [comment]
I Have same problem.
There is solution?

**Comment by bitcrumb** [comment]
This thread on the Apple forum contains extremely helpful information regarding the new Local Network Privacy in iOS 14. It should answer most, if not all of your questions 👍
https://developer.apple.com/forums/thread/663858

**Comment by 0x5e** [comment]
There's a lot of complains in Apple forum about why there's no api to get permission status of localnetwork, but apple developer insists that they will not provide it. I think your long-term plan won't work :( @calrsom 
I would like to share my workaround:
1. When mobile is connected to wifi.
2. Get local ip of your mobile using `getifaddrs` api. (Maybe there's a little risk)
3. Send a http request to your local ip using NSURLSession, any url path is okay.
4. Of course the request failed, but we can differ from the error.code. `NSURLErrorNotConnectedToInternet` means permission not open, else means opened.

**Comment by bitcrumb** [comment]
AFAIK, at this moment in time the only thing you are required to provide is the NSLocalNetworkUsageDescription description in your Info.plist.

Since CocoaAsynSocket using BSD sockets, there is no need (and enforcement of) the `com.apple.developer.networking.multicast` [entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast) yet.

However, it is *highly* encourages to do so, since the expectation is that this will become required with one of the iOS 14.x maintenance updates, see discussion at: https://developer.apple.com/forums/thread/655920.
