### ISSUE TITLE
Deployment target for Xcode12

### ISSUE THREAD

**Issue by fnuky** [robbiehanson/CocoaAsyncSocket#748]
I'm using CocoaAsyncSocket library as a SPM dependency and for Xcode 12 is supported deployment target as iOS 9. In Package.swift is iOS 8, is possible to update it? It makes unnecessary warning.

**Comment by GeroHerkenrath** [comment]
There's actually a PR for this, #741, which has been merged. It just has not (yet?) been released (and pushed to cocoapods) and/or tagged, so the Swift Package Manager doesn't see it. I assume the idea is to collect some more features and perhaps also decide about the version number (currently the PR just increased the patch part of it, but since it could be a breaking change for some older projects there's also a case for incrementing the minor part).

**Comment by K3TZR** [comment]
For those of us using it via Swift PM it would be helpful to have #741 addressed by bumping the tag

**Comment by chrisballinger** [comment]
This is now resolved via https://github.com/robbiehanson/CocoaAsyncSocket/releases/tag/7.6.5
